---
title: "Project Proposal"
author: "Kevin Baer (706252583) and Calvin Vo (806751849)"
format: pdf
editor: visual
---

Hook:

When I (Kevin), was young, I played in a quite a few highly competitive youth chess tournaments. By the time I got into high school, it was fairly for my competitors to be gulping down a pill prior to competition. But I never really understood what it was or why it might be helping them until I caught a glimpse of the label: "[Caffeine pill](https://www.amazon.com/Nutricost-Caffeine-Pills-Serving-Capsules/dp/B01MY5CW7S?th=1)" 100 mg. It seems like everyone else just thought that taking these pills would help with their attention and performance. Now, we can see whether an advantage is truly prescribed, by testing this on the islanders.

Possible Supplements:

-   Caffeine Tablet (100mg) (1 dose)

-   Methamphetamine (10mg)

-   MDMA (50mg)

Study design:

-   All genders, ages 21-29

-   Paired study:

    -   n games played back-to-back (alternating colors, starting with white)

    -   Separately, days later, n games played back-to-back (alternating colors, starting with white)

    -   50% will take a caffeine tablet, 1 hour before the games on day 1, and the other 50% will take on day 2. (Randomly assigned)

-   Should we narrow location down to a specific island (and then we can poll for town, house number pairings)

Response variables:

-   Blood Adrenaline (pg/ml)

-   Play chess white/black (win pct, draws count for 0.5)

Sample size determination:

-   Done using pwr R package.

Data Analysis:

-   Start with a graphical exploration and analysis using data visualizations

-   Then move into summary statistics and tables

-   Statistical test will be a paired t-test.

-   Analysis of residuals

Papers to discuss / compare with:

-   [Link 1](https://pdf.sciencedirectassets.com/271078/1-s2.0-S0924977X16X0017X/1-s2.0-S0924977X17300196/main.pdf?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGMaCXVzLWVhc3QtMSJHMEUCIBDgpmYGrQggWFBWxurn1B9L6qo33y2ie0qZfs8aPTl7AiEA%2BYLfEwGez8lritYEneFJT4Ung%2BgiRodOSnhvST4dFhIqswUILBAFGgwwNTkwMDM1NDY4NjUiDG4CNo368JHbKUiCkCqQBcmgHF5WFe3P3cNn9i2GD8I3Qj7N45fVDphI%2FGpKwfiUZlsJHhF2%2F4BrprBPzMT2e5pc%2B9Ggb%2F1oh9PZCDX1k4xMPA23jDupr3I2wLx3g6P5rpHfubT3cvkFyHxMSPYTX01XoU87LZfggoBzxQwjgwZxSJ63rJ3Ypadr%2BLGg5G%2B0Avd6oSTYtR5vJCpwwSxuLcQmmOWMPIAi8IzdEXci%2BgsTbrXwvwlZF9FXPnQZ%2FKuuVUatfxOafuTyMbZXdF%2Buf%2BhIDCnXptXP0JBOh%2BjcYeLS1JKqzuKh3S87qQ3KkoF0PfCsjqe%2FiNEb%2BGDznW8Q94undhzb2kLmklcEjy0bq1Ps8fB3cj1vuzopB3fCljmYsHQAhzidtRUYs17vf3v3UJvwfg4dsI7tXhS3ZDs2schhyBGuE0JpOwaLxLI3eieaBejP1Ymv6gSJJY%2FaurMSzy%2B%2Fd07sCoFSRS7P%2FWt59e%2FcUjuOnznCvXYtDFOBx7UqAYNl%2FJLylgZgML1ymgXIhprju%2FeCzbWxsbQJ5vnw82V1l3whGhcDjoGn7a0Hk8rrBE3gpquK%2BrLCCxirJtSuTK0HO%2FpsppDDO6rK75z%2Bl73ezsXlcELRr%2FdQtRIdLiB7oDqgiJAGHPjzOS10FvGIpBBLbHwdGYU3NUbkF8vt%2FbzgL6bpBzABVhNbozMDvA%2FXTrxgMj3FBxsscrMbfSTGB7n4ibDVIIF8qgcWXUe3qPzwAr4pKQdrVFH96%2FtozJlyJCGVjyvJsLcSHpYQIiVUCUd%2FOpYXYTWHxfMVdxCffmPp6np2fNkVs3yH0qX0vqsgjHbxr44af9ZyR413ZeeeuNmRVnoekvXAOVh7m%2FewktQkUnUQSp%2FZ%2FgfWGhR8WvNmMMOnxNAGOrEB50mHjRFT228FDNliqS57vXPNeLQKTJp7sXvkoAqAeB3qEqKSWbezLhn68vylgBQPvNJHOYLPulftkd7z%2BoMvmTkBE14oxXp6%2Fb3RBBKgcrWvS%2BONcgfRZPsNenfnLWp7ZVm%2BpPRK8jRW8a%2B1Fs%2FxHuuMqug4jhSwb7bp7SQ0sQkVxB10IcD4cdGO6jrt8ud7Z8AIaO15%2BJ7CT6mqwdoq2c3RNXTWIVU9z552HCYCxVnD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260523T043248Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAQ3PHCVTYUGATXIRJ%2F20260523%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=e30be571d50b6ff514162a704400f5436f8bc747e63e4c557a7bf4f58e3617c6&hash=3757583dda36b9562fbdcfe0d42c08e9d5bebd2d236d6abaf99f33f822a6a49d&host=68042c943591013ac2b2430a89b270f6af2c76d8dfd086a07176afe7c76c2c61&pii=S0924977X17300196&tid=spdf-bd3083ad-59d7-421b-a5f4-deaa3f00ddfe&sid=07c4251e6badc64fac9bfad968d7775eda13gxrqa&type=client&tsoh=d3d3LnNjaWVuY2VkaXJlY3QuY29t&rh=d3d3LnNjaWVuY2VkaXJlY3QuY29t&ua=0f150e5355505a58050c55&rr=a00156bc28a278e5&cc=us)

-   [Link 2](https://pmc.ncbi.nlm.nih.gov/articles/PMC4462044/pdf/CN-13-71.pdf)

-   [Link 3](https://pmc.ncbi.nlm.nih.gov/articles/PMC9415189/pdf/nutrients-14-03367.pdf)

-   [Link 4](https://pmc.ncbi.nlm.nih.gov/articles/PMC5978818/pdf/12152_2018_Article_9354.pdf)

-   [Link 5](https://pdf.sciencedirectassets.com/271877/1-s2.0-S1364661310X00122/1-s2.0-S1364661310002482/main.pdf?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGQaCXVzLWVhc3QtMSJIMEYCIQCY9C09Ak3YxTEYvZdb%2BpSov6hjJqf%2FotRM5AUVhv512QIhALrH0PFowCEprnfPMRJerApkpq%2F1%2B5%2FRMUTgniN5y9BtKrMFCC0QBRoMMDU5MDAzNTQ2ODY1Igx7mQOM8ZhWSfeq6iIqkAUv%2FHrb%2FtScFe9IlVW%2F4iUXtNz3zUha9yBIJliQFhda4pxij6C81eVpSR6kGMr2Z5KlZCvVFjbos%2BAw9XSZvZ4OnEyJAe%2B360EKlkFmw5CvxLJhY1NTeBpyU3qLXyJ1XHXcNVxWvEj8PP4bm1LHxL06wSRkVihuFk2%2BjgFa2fh7EuiJGPiMu5EYpwj%2FmjRYbNJOyFmyaeB1oG7V8Ptui7yrq8y386HA5FYn4GKaMy%2BsKUnYI32eScLbYFn3PaxZ4Ld0JpzcZJ%2B6%2FjVjqXFjmkVWhtyBil3ZFpuFVXpG2coxqNIIZQHRGemDtMThpTdf6tFJhIAQM5Z8IepBR36Mxdd61wwz5YXHcV5uUm15hDXpDOXvLQuS%2BVSNzyG%2FDRQcsBQPAo%2B%2FS2Y9d1WTHM%2FLkjtHedEb1yl0q%2FRIRHiCNebjFTXtGGrClubDztXLS6WXFOjyLaaGSliZC30%2BUMEA5oGTbKMjnGIE1Zsqoz5tisaD7%2BqanlCJ%2BHeU2xfhFCFCBUihJR5RwN9aXg%2FTxHIiZN2G1TAYSvNuELa7okNIv1JmrmmXY%2F2yYA8ClCEt5ahaMPxAlTekPVvkicLPYCYbXseKXTI9qe2yXgyjSs0bUR0cprBU4oNTBSIX9BeWKfxMa%2FRyCidtGwLaslwWOfXwP0cziOcK2vOkaLe1UVRquTshnn0burcUm%2B5fzzJyxeBfV%2FgQ%2BZgL9A3h%2Bz5X9fh9XpVs559%2B8dmfC%2BPBYi65nPZjzCfg4nmFREJ%2BZ6nYejBiMhvFWK1HJhmHpCpfuY7HztDGzhhXH2YFejGEhlEVppN21cdqlz4Gk64SXhbQN1i7Omo3Ajxwj4qDAX0eO4m6k%2FcG3N3qdu2DeAZFyjw3lxFF%2BjC5xcTQBjqwAQF1bteejiAzmr8Zky3iYXXlADrOrJ82OkLRiOvHUg%2BPj4FHFpKqx67Q84%2BkSOy%2Fs9hPbTcw0inP62yDANvorlAaRNP%2Blwit2RWMDxDDOpaCnWMwUZSuG9zm3eKbIFDH3c9y6HjRYpO98fYcQHlq8MvMM9GFLCcBgjm1sDxonEdEyhih1St4hAu%2BNc2U7JQL1HTkUhx1D6lwD5CRyjjtZO31v8eWqEfxbCzWPQSI754T&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260523T044930Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAQ3PHCVTYXWLVP3RF%2F20260523%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=624c2aa3196794a4f50735d15967921dbd96bd3a0bba213446f562bd4673898b&hash=6890fbc8e245525b48faf0a66d122a60898685c047bdd7ca503cca059ca77ec9&host=68042c943591013ac2b2430a89b270f6af2c76d8dfd086a07176afe7c76c2c61&pii=S1364661310002482&tid=spdf-ce6b8938-d851-492a-a243-a7beef5af36e&sid=07c4251e6badc64fac9bfad968d7775eda13gxrqa&type=client&tsoh=d3d3LnNjaWVuY2VkaXJlY3QuY29t&rh=d3d3LnNjaWVuY2VkaXJlY3QuY29t&ua=0f150e5355505908545d52&rr=a0016f325d49cb83&cc=us)
